# Generated by Django 4.2 on 2023-05-26 05:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=50)),
                ('getter', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='../static/img/photo404.jpg', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('description', models.CharField(max_length=2000)),
                ('link', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('avatar', models.ImageField(blank=True, default='../static/img/profile.png', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('fullName', models.CharField(default='похоже, тут ничего нет...', max_length=100)),
                ('education', models.CharField(default='похоже, тут ничего нет...', max_length=100)),
                ('edu_base', models.CharField(default='похоже, тут ничего нет...', max_length=100)),
                ('contacts', models.CharField(default='похоже, тут ничего нет...', max_length=250)),
                ('level', models.CharField(default='похоже, тут ничего нет...', max_length=100)),
                ('chars', models.CharField(default='похоже, тут ничего нет...', max_length=150)),
                ('exp', models.CharField(default='похоже, тут ничего нет...', max_length=200)),
                ('liked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.portfolio')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
