# Generated by Django 4.2 on 2023-05-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_message_chat_remove_message_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
