# Generated by Django 4.2 on 2023-06-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_like_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
    ]
