# Generated by Django 4.2 on 2023-06-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_like_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.userprofile'),
        ),
    ]
