# Generated by Django 4.2 on 2023-05-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_userprofile_avatar_alter_userprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chars',
            field=models.CharField(default='who', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.CharField(default='who', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='edu_base',
            field=models.CharField(default='who', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='who', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exp',
            field=models.CharField(default='who', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='who', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='who', max_length=100),
            preserve_default=False,
        ),
    ]
