# Generated by Django 4.2 on 2023-05-10 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_userprofile_chars_userprofile_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../static/img/photo404.jpg', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('description', models.CharField(max_length=2000)),
                ('link', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/img/profile.png', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chars',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contacts',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='edu_base',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exp',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default='похоже, тут ничего нет...', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
