# Generated by Django 4.2 on 2023-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_message_readen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='readen',
        ),
    ]
