# Generated by Django 4.2 on 2023-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_message_readen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='readen',
        ),
        migrations.AddField(
            model_name='message',
            name='readed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
