# Generated by Django 4.2 on 2023-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_message_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='readed',
        ),
    ]
