# Generated by Django 4.2 on 2023-05-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_message_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='readed',
            field=models.BooleanField(),
        ),
    ]
