# Generated by Django 4.2 on 2023-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_message_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='readed',
        ),
        migrations.AddField(
            model_name='message',
            name='auth',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
