# Generated by Django 4.2 on 2023-05-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_remove_message_readed_message_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='auth',
        ),
    ]
