# Generated by Django 4.2 on 2023-05-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_remove_message_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auth',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
